"""add new column and set not null

Revision ID: 01a1e6c3a2a4
Revises: 4389f9b670da
Create Date: 2026-08-11 20:13:26.501621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01a1e6c3a2a4'
down_revision: Union[str, Sequence[str], None] = '4389f9b670da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add new columns as nullable first
    op.add_column('budgets', sa.Column('budget_type', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('transaction_flow', sa.String(), nullable=True))

    # 2. Backfill budget_type from old budgetType column (preserve existing data)
    op.execute("UPDATE budgets SET budget_type = \"budgetType\" WHERE budget_type IS NULL")

    # 3. Backfill transaction_flow with a sensible default for existing rows
    op.execute("UPDATE transactions SET transaction_flow = 'EXPENSE' WHERE transaction_flow IS NULL")

    # 5. Backfill category on transactions
    op.execute("UPDATE transactions SET category = 'OTHERS' WHERE category IS NULL")

    # 6. NOW tighten to NOT NULL, safely
    op.alter_column('budgets', 'budget_type', nullable=False)
    op.alter_column('budgets', 'created_at', existing_type=postgresql.TIMESTAMP(), nullable=False)
    op.alter_column('transactions', 'transaction_flow', nullable=False)
    op.alter_column('transactions', 'category', existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column('transactions', 'created_at', existing_type=postgresql.TIMESTAMP(), nullable=False)

    # 7. Index changes and old column drop (after data is safely copied)
    op.drop_index(op.f('ix_budgets_budgetType'), table_name='budgets')
    op.create_index(op.f('ix_budgets_budget_type'), 'budgets', ['budget_type'], unique=False)
    op.drop_column('budgets', 'budgetType')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('transactions', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('budgets', sa.Column('budgetType', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_budgets_budget_type'), table_name='budgets')
    op.create_index(op.f('ix_budgets_budgetType'), 'budgets', ['budgetType'], unique=False)
    op.alter_column('budgets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('transactions', 'transaction_flow')
    op.drop_column('budgets', 'budget_type')
    # ### end Alembic commands ###
