"""add created_month to budgets

Revision ID: 5a090b2b8aa2
Revises: 1dad07b8d36d
Create Date: 2026-07-30 22:51:53.116553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a090b2b8aa2'
down_revision: Union[str, Sequence[str], None] = '1dad07b8d36d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('created_month', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budgets', 'created_month')
    # ### end Alembic commands ###
