"""add_deleted_at_to_transactions

Revision ID: d2b14d67747b
Revises: 1f63886cfe69
Create Date: 2026-07-25 01:29:20.251249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2b14d67747b'
down_revision: Union[str, Sequence[str], None] = '1f63886cfe69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'deleted_at')
    # ### end Alembic commands ###
